### ISSUE TITLE
Web Driver Err

### ISSUE THREAD

**Issue by erdemkahraman** [birolemekli/tcdd-bilet-yer-kontrol#6]
Selamlar,
Programda sanırım ChromeDriver versiyonu ile alakalı bir sorun buldum.

```
erdem@ubuntu:~/Desktop/tcdd-bilet-yer-kontrol$ python3 main.py rdm.khrmn@gmail.com
Biniş yerinizi giriniz. Ör:Ankara Gar
Gebze
İniş yerinizi giriniz. Ör:İstanbul(Pendik)
Eryaman YHT
Gideceğiniz günü giriniz. Ör:18.07.2021
26.12.2022
Saati giriniz. Ör:15:00
15:00
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    driver=driverSetting()
  File "main.py", line 10, in driverSetting
    return DriverSetting.DriverSetting().driverUP()
  File "/home/erdem/Desktop/tcdd-bilet-yer-kontrol/DriverSetting.py", line 11, in driverUP
    driver = webdriver.Chrome(options=chrome_options)
  File "/home/erdem/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/erdem/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/home/erdem/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/erdem/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/erdem/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/erdem/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79
Stacktrace:
#0 0x5581eeaee479 <unknown>

```

**Comment by erdemkahraman** [comment]
Sorunu çözdüm chrome driver ve chrome sürümü aynı olmalıymış dökümana not olarak ekleyebilirsiniz.
